apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: prod
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-services
  namespace: prod
spec:
  action: ALLOW
  rules:
  - from:
    - source:
      namespaces: ["prod", "ingress-nginx"]
    to:
    - operation:
        ports: ["8000"]