[kubernetes_local]
localhost ansible_connection=local

[kubernetes_local:vars]
ansible_python_interpreter=/usr/bin/python3
env=local
kube_context=minikube

[kubernetes_prod]
localhost ansible_connection=local

[kubernetes_prod:vars]
ansible_python_interpreter=/usr/bin/python3
env=prod
k8s_cluster_name=capstone-eks
aws_region=us-east-1

[kubernetes:children]
kubernetes_local
kubernetes_prod